# Generated by Django 4.1.7 on 2023-02-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user_user_list_alter_userlist_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='users',
        ),
        migrations.AddField(
            model_name='userlist',
            name='users',
            field=models.ManyToManyField(to='database.user'),
        ),
    ]
