# Generated by Django 4.1.7 on 2023-02-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_userlist_users_userlist_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='users',
        ),
        migrations.AlterField(
            model_name='party',
            name='user_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partys', to='database.userlist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='database.userlist'),
        ),
    ]
