# Generated by Django 4.1.7 on 2023-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_userlist_users_alter_party_user_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_list',
        ),
        migrations.AddField(
            model_name='userlist',
            name='users',
            field=models.ManyToManyField(to='database.user'),
        ),
    ]
