# Generated by Django 4.1.7 on 2023-02-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_user_user_list_userlist_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='user_list',
        ),
        migrations.AddField(
            model_name='party',
            name='users',
            field=models.ManyToManyField(to='database.user'),
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
