# Generated by Django 4.1.7 on 2023-04-23 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_party_user_list_party_users_delete_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='database.user'),
        ),
    ]
