# Generated by Django 4.1.7 on 2023-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_user_inside_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='city',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
