# Generated by Django 4.1.7 on 2023-05-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_user_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticUserCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(default='Пользователь', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=500)),
                ('user_id', models.CharField(max_length=50)),
                ('inside_id', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticPartyCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('discription', models.TextField(max_length=500)),
                ('user_now', models.CharField(max_length=10)),
                ('user_max', models.CharField(max_length=10)),
                ('leader_id', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, null=True, to='database.user')),
            ],
        ),
    ]
