# Generated by Django 4.1.7 on 2023-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_party_category_statisticpartycreate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='lat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='party',
            name='lon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='statisticpartycreate',
            name='lat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='statisticpartycreate',
            name='lon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='statisticpartydelete',
            name='lat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='statisticpartydelete',
            name='lon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
