# Generated by Django 4.1.7 on 2023-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_party_lat_party_lon_statisticpartycreate_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticpartydelete',
            name='choice',
            field=models.CharField(default=123123, max_length=50),
            preserve_default=False,
        ),
    ]
