# Generated by Django 4.1.7 on 2023-05-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_remove_statisticpartydelete_choice_party_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='lon',
            field=models.CharField(max_length=50),
        ),
    ]
