# Generated by Django 4.1.7 on 2023-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_party_lat_alter_party_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticpartycreate',
            name='users',
        ),
        migrations.RemoveField(
            model_name='statisticpartydelete',
            name='users',
        ),
        migrations.DeleteModel(
            name='StatisticUserCreate',
        ),
        migrations.DeleteModel(
            name='StatisticUserDelete',
        ),
        migrations.AlterField(
            model_name='party',
            name='age',
            field=models.CharField(max_length=50, verbose_name='Средний возраст пати'),
        ),
        migrations.AlterField(
            model_name='party',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='party',
            name='choice',
            field=models.CharField(max_length=50, verbose_name='Тип локации'),
        ),
        migrations.AlterField(
            model_name='party',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='party',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='party',
            name='discription',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='party',
            name='lat',
            field=models.CharField(max_length=50, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='party',
            name='leader_id',
            field=models.CharField(max_length=50, verbose_name='Ник Лидера'),
        ),
        migrations.AlterField(
            model_name='party',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='party',
            name='lon',
            field=models.CharField(max_length=50, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='party',
            name='user_max',
            field=models.CharField(max_length=10, verbose_name='Максимальное кол-во юзеров'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата созд'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discription',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inside_id',
            field=models.CharField(max_length=50, verbose_name='Внутренний код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(default='Пользователь', max_length=50, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=50, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='StatisticPartyCreate',
        ),
        migrations.DeleteModel(
            name='StatisticPartyDelete',
        ),
    ]
